version: '3.5'
services:
  php:
    container_name: php8.0-xdebug
    build:
      context: https://github.com/tbreuss/docker-php-builtin-server.git
      args:
        - PHP_IMAGE=8.0-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./:/root-dir
